# Generated by Django 2.0.3 on 2018-03-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180314_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasemanagement',
            name='ScheduleTime',
            field=models.DateField(null=True, verbose_name='ক্ষুরারােগ টিকা প্রদাণের সময়'),
        ),
        migrations.AlterField(
            model_name='fmdschedule',
            name='NextScheduleTime',
            field=models.DateField(null=True, verbose_name='পরবর্তী প্রদাণের তারিখ'),
        ),
    ]
