# Generated by Django 2.0.3 on 2018-03-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailyRoutine', models.TextField(verbose_name='Daily Routine')),
            ],
        ),
    ]
