# Generated by Django 2.0.3 on 2018-03-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grassName', models.CharField(max_length=100, verbose_name='ঘাস পরিচিতি')),
                ('suitableField', models.TextField(verbose_name='উপযোগী জমি')),
                ('plantationTime', models.TextField(verbose_name='চাষের সময়')),
                ('plantationProcedure', models.TextField(verbose_name='চাষের পদ্ধতিঃ')),
                ('fertilizer', models.TextField(verbose_name='সার')),
                ('waterIrrigation', models.TextField(verbose_name='পানি সেচ')),
                ('grassCollection', models.TextField(verbose_name='ঘাস সংগ্রহ')),
                ('problemAndCaution', models.TextField(verbose_name='সমস্যা ও সতর্কতা')),
            ],
        ),
    ]
