# Generated by Django 2.0.3 on 2018-03-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_grass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmdschedule',
            name='ScheduleTime',
        ),
        migrations.AddField(
            model_name='diseasemanagement',
            name='ScheduleTime',
            field=models.DateTimeField(null=True, verbose_name='ক্ষুরারােগ টিকা প্রদাণের সময়'),
        ),
    ]
