# Generated by Django 2.0.3 on 2018-03-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180314_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseaseName', models.CharField(max_length=100, verbose_name='Disease Name')),
                ('medicineName', models.TextField(verbose_name='Medicine Name')),
            ],
        ),
    ]
