# Generated by Django 2.0.3 on 2018-04-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_no', models.CharField(max_length=100, verbose_name='গরু নং ')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='টিকার নাম')),
            ],
        ),
        migrations.DeleteModel(
            name='Cow_Detail',
        ),
        migrations.RemoveField(
            model_name='fmdschedule',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='diseasemanagement',
            name='cowNo',
        ),
        migrations.AddField(
            model_name='diseasemanagement',
            name='NextScheduleTime',
            field=models.DateField(null=True, verbose_name='পরবর্তী প্রদাণের তারিখ'),
        ),
        migrations.AlterField(
            model_name='diseasemanagement',
            name='ScheduleTime',
            field=models.DateField(null=True, verbose_name='ক্টিকা প্রদাণের সময়'),
        ),
        migrations.DeleteModel(
            name='FMDSchedule',
        ),
    ]
