# Generated by Django 2.0.3 on 2018-04-02 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180401_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_info', models.TextField(verbose_name='প্রজণন সংক্রান্ত তথ্য')),
                ('breeding_date', models.DateField(null=True, verbose_name='বীজ দেওয়ার তারিখ')),
                ('expacted_delivery_date', models.DateField(null=True, verbose_name='বাচ্চা প্রসবের সম্ভাব্য তারিখ')),
                ('delivery_date', models.DateField(null=True, verbose_name='বাচ্চা প্রসবের তারিখ')),
                ('cow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cow', verbose_name='গরু নং')),
            ],
            options={
                'ordering': ['breeding_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='diseasemanagement',
            options={'ordering': ['ScheduleTime']},
        ),
        migrations.AlterField(
            model_name='diseasemanagement',
            name='ScheduleTime',
            field=models.DateField(null=True, verbose_name='টিকা প্রদাণের সময়'),
        ),
        migrations.AlterField(
            model_name='diseasemanagement',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Disease', verbose_name='টিকার নাম'),
        ),
    ]
