# Generated by Django 2.0.3 on 2018-04-02 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180402_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField(default=0, verbose_name='গরুর বয়স')),
                ('weight', models.FloatField(default=0, verbose_name='গরুর ওজন')),
                ('number_of_teeth', models.IntegerField(default=0, verbose_name='দাঁত সংখ্যা')),
                ('status', models.CharField(choices=[('M', 'Milking'), ('D', 'Dry Preiod'), ('C', 'Calf')], max_length=1)),
                ('cow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cow', verbose_name='গরু নং')),
            ],
        ),
    ]
