# Generated by Django 2.0.3 on 2018-04-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180403_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowdetail',
            name='status',
            field=models.CharField(choices=[('Milking', 'Milking'), ('Dry Preiod', 'Dry Preiod'), ('Calf', 'Calf')], max_length=1, verbose_name='গরুর ধরন'),
        ),
    ]
