# Generated by Django 2.0.3 on 2018-04-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180404_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowdetail',
            name='status',
            field=models.CharField(choices=[('Milking', 'Milking'), ('Dry Preiod', 'Dry Preiod'), ('Calf', 'Calf')], max_length=10, verbose_name='গরুর ধরন'),
        ),
    ]
