# Generated by Django 2.0.3 on 2018-04-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180404_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkManageMent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='তারিখ')),
                ('milk_quantity', models.FloatField(default=0, verbose_name='দুধের পরিমান')),
                ('cow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cow', verbose_name='গরু নং')),
            ],
        ),
    ]
