# Generated by Django 2.0.3 on 2018-04-05 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_milkmanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='তারিখ')),
                ('mixed_food', models.FloatField(default=0, verbose_name='দানাদার খাদ্য(কে.জি)')),
                ('grass', models.FloatField(default=0, verbose_name='ঘাস(ে.জি)')),
                ('khor', models.FloatField(default=0, verbose_name='খর(ে.জি)')),
                ('water', models.FloatField(default=0, verbose_name='পানি(লিটার)')),
                ('cow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cow', verbose_name='গরু নং')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='milkmanagement',
            options={'ordering': ['date']},
        ),
    ]
