# Generated by Django 2.0.3 on 2018-05-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20180405_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About Page Contents'},
        ),
        migrations.AlterModelOptions(
            name='biosecurity',
            options={'verbose_name_plural': 'Bioseceurty Page Contents'},
        ),
        migrations.AlterModelOptions(
            name='breeding',
            options={'ordering': ['breeding_date'], 'verbose_name_plural': 'Breeding Records'},
        ),
        migrations.AlterModelOptions(
            name='cowdetail',
            options={'verbose_name_plural': 'Cow Records'},
        ),
        migrations.AlterModelOptions(
            name='dailyroutine',
            options={'verbose_name_plural': 'Daily Routine Page Contents'},
        ),
        migrations.AlterModelOptions(
            name='diseasemanagement',
            options={'ordering': ['ScheduleTime'], 'verbose_name_plural': 'Vaacine Records'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Sticky Note Page Contents'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['upload_time'], 'verbose_name_plural': 'Upload File'},
        ),
        migrations.AlterModelOptions(
            name='foodmanagement',
            options={'ordering': ['date'], 'verbose_name_plural': 'Food Records'},
        ),
        migrations.AlterModelOptions(
            name='grass',
            options={'verbose_name_plural': 'Grass Informations'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name_plural': 'Medicine Informations'},
        ),
        migrations.AlterModelOptions(
            name='milkmanagement',
            options={'ordering': ['date'], 'verbose_name_plural': 'Milk Records'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-upload_time'], 'verbose_name_plural': 'Slide Photos'},
        ),
        migrations.AddField(
            model_name='foodmanagement',
            name='grass_cost',
            field=models.FloatField(default=0, verbose_name='ঘাসের দাম'),
        ),
        migrations.AddField(
            model_name='foodmanagement',
            name='khor_cost',
            field=models.FloatField(default=0, verbose_name='খড়ের দাম'),
        ),
        migrations.AddField(
            model_name='foodmanagement',
            name='mixed_food_price',
            field=models.FloatField(default=0, verbose_name='দানাদার দাম'),
        ),
        migrations.AddField(
            model_name='milkmanagement',
            name='milk_price',
            field=models.FloatField(default=0, verbose_name='দুধের দাম'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(help_text='About Page Contents', verbose_name='About Advance Agro'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='cow_no',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='গরু নং '),
        ),
        migrations.AlterField(
            model_name='cowdetail',
            name='status',
            field=models.CharField(choices=[('Milking', 'Milking'), ('Dry Preiod', 'Dry Preiod'), ('Calf', 'Calf'), ('Fattening', 'Fattening')], max_length=10, verbose_name='গরুর ধরন'),
        ),
    ]
