# Generated by Django 2.0.3 on 2018-05-13 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20180512_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='তারিখ')),
                ('costing_amount', models.FloatField(default=0, verbose_name='খরচের পরিমান')),
                ('costing_description', models.CharField(max_length=200, verbose_name='খরচের বর্ণনা')),
                ('cow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cow', verbose_name='গরু নং')),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='তারিখ')),
                ('earning_amount', models.FloatField(default=0, verbose_name='আয়ের পরিমান')),
                ('earning_description', models.CharField(max_length=200, verbose_name='আয়ের বর্ণনা')),
                ('cow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cow', verbose_name='গরু নং')),
            ],
        ),
    ]
