# Generated by Django 2.0.3 on 2018-05-14 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_costing_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowdetail',
            name='cow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cow', verbose_name='গরু নং'),
        ),
    ]
